builds:
  - main: arcd/main.go
    binary: arcd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - balls
      - docs
      - Merge pull request
      - Merge branch

dockers:
  - image: evilsocket/arc
    latest: true
    tag_template: '{{ .Tag }}' 

tag_template: '{{ .Tag }}'
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
      - LICENSE
      - README.md
      - Dockerfile
      - sample_config.json
      - arc/**/*
