builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    binary: arc
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    ignore:
      # gocode/pkg/mod/github.com/dblohm7/wingoes@v0.0.0-20240119213807-a09d6be7affa/com/stream.go:127:10: maxStreamRWLen (untyped int constant 4294967295) overflows int
      - goos: windows
        goarch: arm
    main: ./cmd/arc

changelog:
  sort: asc
  filters:
    exclude:
      - balls
      - docs
      - Merge pull request
      - Merge branch
      - Releasing v

archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
        - LICENSE
        - README.md
        - Dockerfile
        - sample_config.toml
