builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    binary: arc
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    main: ./cmd/arc

changelog:
  sort: asc
  filters:
    exclude:
      - balls
      - docs
      - Merge pull request
      - Merge branch
      - Releasing v

archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
        - LICENSE
        - README.md
        - Dockerfile
        - sample_config.toml
